

import { Inter } from "next/font/google";
import "./globals.css";
import StoreProvider from "./rtk/Provider";

// import { Navbar } from "flowbite-react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "todo list",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <StoreProvider >
      <html lang="en" >

        <body className={inter.className}>
          {/* <Main /> */}
          {children}
        </body>
      </html>
    </StoreProvider>
  );
}
